// GENERATED by `pnpm --filter @workspace/api-server run images:seed` — do not edit.
// Starter records for the governed brand image library. Loaded once by
// imageLibraryStore when no snapshot has ever been seeded (fresh database),
// so production boots with a working library. The image bytes live in the
// shared object-storage bucket under <PRIVATE_OBJECT_DIR>/seed/.

import type { BrandImageRecord } from "./imageLibraryStore";

export const BRAND_IMAGE_SEED: BrandImageRecord[] = [
  {
    "id": "img-seed-telecom-tower",
    "objectPath": "/objects/seed/brand-telecom-tower",
    "filename": "telecom_tower.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 853,
    "label": "Telecom tower against a blue sky",
    "tags": [
      "network",
      "infrastructure",
      "tower",
      "cover"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-fiber-optics",
    "objectPath": "/objects/seed/brand-fiber-optics",
    "filename": "fiber_optics.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 720,
    "label": "Fiber optic strands in blue light",
    "tags": [
      "network",
      "fiber",
      "technology",
      "abstract"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-office-team",
    "objectPath": "/objects/seed/brand-office-team",
    "filename": "office_team_meeting.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 771,
    "label": "Team meeting in a modern office",
    "tags": [
      "team",
      "office",
      "people",
      "collaboration"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-datacenter",
    "objectPath": "/objects/seed/brand-datacenter",
    "filename": "datacenter_corridor.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 675,
    "label": "Data centre server corridor",
    "tags": [
      "datacenter",
      "technology",
      "infrastructure"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-city-skyline",
    "objectPath": "/objects/seed/brand-city-skyline",
    "filename": "city_skyline_dusk.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 720,
    "label": "City skyline at dusk",
    "tags": [
      "city",
      "urban",
      "skyline",
      "cover"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-field-engineer",
    "objectPath": "/objects/seed/brand-field-engineer",
    "filename": "field_engineer.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 771,
    "label": "Field engineer at an antenna site",
    "tags": [
      "engineer",
      "people",
      "network",
      "field"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-customer-smartphone",
    "objectPath": "/objects/seed/brand-customer-smartphone",
    "filename": "customer_smartphone.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 853,
    "label": "Customer using a smartphone",
    "tags": [
      "customer",
      "smartphone",
      "people",
      "retail"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-abstract-network",
    "objectPath": "/objects/seed/brand-abstract-network",
    "filename": "abstract_network.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 711,
    "label": "Abstract blue network connections",
    "tags": [
      "abstract",
      "technology",
      "network",
      "background",
      "cover"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-football-stadium",
    "objectPath": "/objects/seed/brand-football-stadium",
    "filename": "football_stadium.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 721,
    "label": "Football stadium under floodlights",
    "tags": [
      "football",
      "sports",
      "sponsorship",
      "stadium"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  },
  {
    "id": "img-seed-support-agent",
    "objectPath": "/objects/seed/brand-support-agent",
    "filename": "support_agent.jpg",
    "contentType": "image/jpeg",
    "width": 1280,
    "height": 731,
    "label": "Customer support agent with headset",
    "tags": [
      "customer",
      "support",
      "people",
      "service"
    ],
    "uploadedBy": "Brand Library Seed",
    "uploadedAt": "2026-07-21T00:08:14.320Z"
  }
];
