// Seed the governed brand image library.
//
// Uploads the curated starter images to object storage under DETERMINISTIC
// object names (`<PRIVATE_OBJECT_DIR>/seed/brand-<slug>`), probes their pixel
// dimensions, and regenerates `src/data/brandImageSeed.ts` — the committed
// manifest the store loads on first boot (fresh database) so production comes
// up with a working library without any prod-side scripting. Re-running
// overwrites the same objects in place — idempotent, mirror of qdrant:seed.
//
// The bucket is shared between the workspace and deployments, so uploading
// once from dev is enough; only the RECORDS travel via the committed manifest.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { imageSize } from "image-size";
import { objectStorageClient } from "../lib/objectStorage";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "../../../..");
const SOURCE_DIR = path.join(REPO_ROOT, "attached_assets/stock_images");
const MANIFEST_PATH = path.join(HERE, "../data/brandImageSeed.ts");

interface SeedSpec {
  file: string;
  slug: string;
  label: string;
  tags: string[];
}

const SPECS: SeedSpec[] = [
  { file: "telecom_tower.jpg", slug: "telecom-tower", label: "Telecom tower against a blue sky", tags: ["network", "infrastructure", "tower", "cover"] },
  { file: "fiber_optics.jpg", slug: "fiber-optics", label: "Fiber optic strands in blue light", tags: ["network", "fiber", "technology", "abstract"] },
  { file: "office_team_meeting.jpg", slug: "office-team", label: "Team meeting in a modern office", tags: ["team", "office", "people", "collaboration"] },
  { file: "datacenter_corridor.jpg", slug: "datacenter", label: "Data centre server corridor", tags: ["datacenter", "technology", "infrastructure"] },
  { file: "city_skyline_dusk.jpg", slug: "city-skyline", label: "City skyline at dusk", tags: ["city", "urban", "skyline", "cover"] },
  { file: "field_engineer.jpg", slug: "field-engineer", label: "Field engineer at an antenna site", tags: ["engineer", "people", "network", "field"] },
  { file: "customer_smartphone.jpg", slug: "customer-smartphone", label: "Customer using a smartphone", tags: ["customer", "smartphone", "people", "retail"] },
  { file: "abstract_network.jpg", slug: "abstract-network", label: "Abstract blue network connections", tags: ["abstract", "technology", "network", "background", "cover"] },
  { file: "football_stadium.jpg", slug: "football-stadium", label: "Football stadium under floodlights", tags: ["football", "sports", "sponsorship", "stadium"] },
  { file: "support_agent.jpg", slug: "support-agent", label: "Customer support agent with headset", tags: ["customer", "support", "people", "service"] },
];

function parsePrivateDir(): { bucketName: string; prefix: string } {
  const dir = process.env.PRIVATE_OBJECT_DIR || "";
  if (!dir.startsWith("/")) {
    throw new Error("PRIVATE_OBJECT_DIR is not configured (expected /<bucket>/<prefix>)");
  }
  const parts = dir.slice(1).split("/");
  const bucketName = parts[0]!;
  const prefix = parts.slice(1).join("/");
  if (!bucketName || !prefix) {
    throw new Error(`PRIVATE_OBJECT_DIR looks malformed: ${dir}`);
  }
  return { bucketName, prefix };
}

async function main(): Promise<void> {
  const { bucketName, prefix } = parsePrivateDir();
  const bucket = objectStorageClient.bucket(bucketName);
  const generatedAt = new Date().toISOString();

  const records: Array<Record<string, unknown>> = [];
  for (const spec of SPECS) {
    const filePath = path.join(SOURCE_DIR, spec.file);
    if (!fs.existsSync(filePath)) {
      throw new Error(`Missing source image: ${filePath}`);
    }
    const bytes = fs.readFileSync(filePath);
    const dims = imageSize(bytes);
    if (dims.type !== "jpg" && dims.type !== "png") {
      throw new Error(`${spec.file}: unsupported image type ${dims.type}`);
    }
    const contentType = dims.type === "png" ? "image/png" : "image/jpeg";
    const entityId = `seed/brand-${spec.slug}`;
    const objectName = `${prefix}/${entityId}`;
    await bucket.file(objectName).save(bytes, {
      contentType,
      resumable: false,
      metadata: { cacheControl: "private, max-age=86400" },
    });
    records.push({
      id: `img-seed-${spec.slug}`,
      objectPath: `/objects/${entityId}`,
      filename: spec.file,
      contentType,
      width: dims.width,
      height: dims.height,
      label: spec.label,
      tags: spec.tags,
      uploadedBy: "Brand Library Seed",
      uploadedAt: generatedAt,
    });
    process.stdout.write(`uploaded ${objectName} (${dims.width}x${dims.height})\n`);
  }

  const manifest = `// GENERATED by \`pnpm --filter @workspace/api-server run images:seed\` — do not edit.
// Starter records for the governed brand image library. Loaded once by
// imageLibraryStore when no snapshot has ever been seeded (fresh database),
// so production boots with a working library. The image bytes live in the
// shared object-storage bucket under <PRIVATE_OBJECT_DIR>/seed/.

import type { BrandImageRecord } from "./imageLibraryStore";

export const BRAND_IMAGE_SEED: BrandImageRecord[] = ${JSON.stringify(records, null, 2)};
`;
  fs.writeFileSync(MANIFEST_PATH, manifest);
  process.stdout.write(`wrote ${MANIFEST_PATH} (${records.length} records)\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
